import os
import subprocess

# Define filenames
tex_filename = "songbook.tex"
pdf_filename = "songbook.pdf"

# Step 1: Run the Bash script to generate the LaTeX file
print("Generating LaTeX file...")
subprocess.run(["bash", "generate.sh"], stdout=open(tex_filename, "w"), check=True)

# Step 2: Compile the LaTeX file into a PDF using pdflatex
print("Compiling LaTeX to PDF...")
subprocess.run(["pdflatex", tex_filename], check=True)

# Step 3: Run pdflatex again for table of contents links (recommended)
print("Running second compilation for TOC links...")
subprocess.run(["pdflatex", tex_filename], check=True)

# Step 4: Cleanup auxiliary files generated by LaTeX
for ext in [".aux", ".log", ".out", ".toc"]:
    aux_file = tex_filename.replace(".tex", ext)
    if os.path.exists(aux_file):
        os.remove(aux_file)

print(f"PDF successfully generated: {pdf_filename}")

