#!/bin/bash

# Start the LaTeX document
echo "% Autogenerated Songbook"
echo "\documentclass[a4paper,10pt]{article}"
echo "\usepackage[T1]{fontenc}"
echo "\usepackage[lmargin=2cm, rmargin=2cm, tmargin=2cm, bmargin=2cm]{geometry}" # Smaller margins
echo "\usepackage{lmodern}"
echo "\usepackage{listings}"
echo "\usepackage{titlesec}"                                   # Reduce spacing before/after sections
echo "\usepackage{setspace}"                                   # Fine-tune line spacing
echo "\usepackage{hyperref}"                                   # Enable clickable links
echo "\hypersetup{colorlinks=true, linkcolor=blue, hidelinks}" # Clickable but without boxes

# Reduce line spacing even more
echo "\linespread{0.9}"
echo "\titleformat{\section}[block]{\normalfont\large\bfseries}{}{0pt}{}"
echo "\titlespacing{\section}{0pt}{2pt}{2pt}" # Reduce space around section titles

# Title of the Songbook
echo "\title{The Real Guitar Songbook}"
echo "\author{Robert Machovec}"
echo "\date{\today}"
echo "\begin{document}"
echo "\maketitle"

# Change Table of Contents heading
echo "\renewcommand{\contentsname}{Setlist}"
echo "\tableofcontents"

echo "\newpage"

# lstlisting settings for proper page breaks
echo "\lstset{"
echo "  basicstyle=\small\ttfamily,"
echo "  breaklines=true,"        # Allow line breaking
echo "  breakatwhitespace=true," # Only break at whitespace (empty lines)
echo "  prebreak=\mbox{},"       # Prevents breaking in the middle of a word
echo "  keepspaces=true"         # Keeps formatting of spaces
echo "}"

# Loop through each song file in the songs/ directory
for file in songs/*.txt; do
    filename=$(basename -- "$file" .txt)          # Remove path and extension
    bandname=$(echo "$filename" | cut -d'-' -f1)  # Extract band name
    songname=$(echo "$filename" | cut -d'-' -f2-) # Extract song name

    # Replace underscores with spaces for display purposes
    bandname=$(echo "$bandname" | tr '_' ' ')
    songname=$(echo "$songname" | tr '_' ' ')

    # Ensure LaTeX properly displays the section title in monospace font
    echo "\phantomsection"                           # Ensure correct hyperlink target
    echo "\section*{\texttt{$bandname - $songname}}" # Display as monospace text

    # Add clickable entry in TOC with monospace font
    echo "\addcontentsline{toc}{section}{\texorpdfstring{\texttt{$bandname - $songname}}{$bandname - $songname}}"

    # Include song content
    echo "\lstinputlisting{$file}"
    echo "\newpage" # Page break between songs
done

# End the LaTeX document
echo "\end{document}"
